### ISSUE TITLE
How to use addon

### ISSUE THREAD

**Issue by reaganch** [ramkumar-kr/containers-sync#2]
I'm a little unclear how to use this addon. I have created a few containers on one computer and would like to sync it to another computer. I have the Containers Sync addon installed on both computers, but am unable to figure out how to sync the containers from one to the other. Does synchronisation happen through the Firefox account?

**Comment by ramkumar-kr** [comment]
Hi,

Yes, Synchronization happens via the Firefox account.

Let us say, we need to sync from computer A to B.
1. Sign in to the firefox account in both computers
2. Click the backup button in the computer A
3. Sync your account in both computers A and B (in order)
4. Click the restore button in computer B.

Let me know if you have any more trouble in syncing the containers

**Comment by reaganch** [comment]
Thanks for that! It worked only after I made a change to one of the containers in computer A, not before.
On a separate note, I realise your FAQs mention this is currently not possible using the available API, but it would be really helpful if the list of sites specified to open in a container could be synchronised between computers too.
Cheers!
