### ISSUE TITLE
Reset button removes all containers without undo option or warning about full consequences

### ISSUE THREAD

**Issue by umcdwarf** [ramkumar-kr/containers-sync#3]
As mentioned in readme:
>What does the reset button in the popup do?
>It will remove all containers from your device and also from the sync storage

Why is that so? By common sense, it should remove containers from local device only, but keep those in sync storage for further restoring. Moreover, there is no warning for such dangerous action, nor feedback afterwards. Such operations **must** prompt user for confirmation before simply deleting everything.

**Comment by ramkumar-kr** [comment]
Hi,

I agree that reset is a dangerous operation and has no prompt or warning.
I'm working on a better UI for the addon with visual feedback which may take some time.
Meanwhile, I have decided to remove the reset functionality from the addon entirely.

**Comment by umcdwarf** [comment]
>Meanwhile, I have decided to remove the reset functionality from the addon entirely.

Fair move.
Best wishes to you and your project.
